GET http://localhost:5000/users/628e116c35dbc45b2ad49ad5

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "username":"a",
    "password":"a",
    "newsletter":false
}

###

PUT http://localhost:3000/users
Content-Type: application/json

{
    "_id":"628b89a4fba196c1ff3bb9b2",
    "newsletter":false
}

###

DELETE  http://localhost:3000/users/628b89a4fba196c1ff3bb9b2

###