GET http://localhost:5000/users/
###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "username":"isabea",
    "password":"21"
}

###

POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "username":"isabelaa",
    "password":"1",
    "newsletter":true
}

###

PUT http://localhost:3000/users
Content-Type: application/json

{
    "_id":"628b89a4fba196c1ff3bb9b2",
    "newsletter":false
}

###

DELETE  http://localhost:3000/users/628b89a4fba196c1ff3bb9b2

###